/**
 * Risk-warning checks for SmartEdit.
 *
 * Checks file paths, edit content, and line ranges against
 * dangerous patterns to surface advisory warnings. Never blocks or
 * prompts for approval — all checks emit warnings as matchNotes.
 *
 * The effective level is controlled by the SMART_EDIT_APPROVAL_LEVEL
 * environment variable (never_prompt | prompt_on_dangerous | prompt_always).
 * The env/type names are kept for compatibility; the behavior is
 * advisory risk warnings only, never a blocking approval gate.
 */

import type { EditItem } from "../core/types";
import { resolve } from "path";
import { realpath, stat, open } from "fs/promises";
import { loadConfig } from "../config/schema.js";

// ─── Types ─────────────────────────────────────────────────────────────

export type ApprovalLevel = "never_prompt" | "prompt_on_dangerous" | "prompt_always";

export interface ApprovalConfig {
  /** Level controlling when risk-warning checks are active */
  level: ApprovalLevel;
  /** Glob-style patterns for dangerous file paths */
  dangerousPathPatterns: readonly string[];
  /** Regex patterns to search for in edit text (old/new, symbolic, structural) */
  dangerousSymbolPatterns: ReadonlyArray<{ name: string; regex: RegExp }>;
  /** First N lines of entry-point files are considered critical */
  criticalLineRange: number;
}

export interface SafetyCheckResult {
  /** True when no dangerous patterns were matched */
  safe: boolean;
  /** Human-readable risk-warning messages (advisory, never blocking) */
  warnings: string[];
  /** Effective level used */
  level: ApprovalLevel;
}

// ─── Environment ───────────────────────────────────────────────────────

const VALID_LEVELS = new Set<ApprovalLevel>([
  "never_prompt",
  "prompt_on_dangerous",
  "prompt_always",
]);

function readApprovalLevelFromEnv(): ApprovalLevel {
  return loadConfig().approvalLevel;
}

// ─── Auto-generated file detection ────────────────────────────────────

const AUTO_GENERATED_MARKERS: readonly string[] = [
  "DO NOT EDIT",
  "auto-generated",
  "Auto-generated",
  "@generated",
  "GENERATED FILE",
  "This file is generated",
  "generated by",
  "Generated by",
  "// Code generated",
  "# Generated by",
];

const AUTO_GENERATED_CHECK_LINES = 10;

// ─── Default patterns ──────────────────────────────────────────────────

/**
 * Glob-style patterns for file paths that are considered dangerous to edit.
 * Supports ** for recursive matching and * for single-segment wildcard.
 * Note: config* matches any path containing "config".
 */
export const DANGEROUS_PATH_PATTERNS: readonly string[] = [
  "**/main.ts",
  "**/main.js",
  "**/index.ts",
  "**/index.js",
  "**/config*",
  "**/*config*",
  "**/.env.*",
  "**/.env*",
  "**/__init__*",
  "**/Dockerfile*",
  "**/ci/**",
  "**/.github/**",
  "**/.gitlab-ci.yml",
  // More specific infra patterns before generic YAML
  "**/k8s/**",
  "**/kubernetes/**",
  "**/terraform/**",
  "**/tf/**",
  "**/*.yaml",
  "**/*.yml",
];

/**
 * Named regex patterns for dangerous symbols / code patterns in edit content.
 * Each entry has a human-readable name and the regex to match.
 */
export const DANGEROUS_SYMBOL_PATTERNS: ReadonlyArray<{ name: string; regex: RegExp }> = [
  { name: "main() function", regex: /function\s+main\s*\(/ },
  { name: "init() function", regex: /function\s+init\s*\(/ },
  { name: "constructor method", regex: /constructor\s*\([^)]*\)\s*\{/ },
  { name: "process.env access", regex: /\bprocess\.env\b/ },
  { name: "Python __init__", regex: /def\s+__init__\s*\(/ },
  { name: "child_process require", regex: /require\(\s*['"]child_process['"]\s*\)/ },
  { name: "child_process import", regex: /import\s+.*\bfrom\s+['"]child_process['"]/ },
  { name: "fs.writeFile", regex: /\bfs\.writeFile\b/ },
  { name: "fs.appendFile", regex: /\bfs\.appendFile\b/ },
  { name: "fs promises write", regex: /\bfsPromises\.writeFile\b/ },
  { name: "server .listen()", regex: /\.listen\s*\(/ },
  { name: "route handler", regex: /(?:\b(?:app|router)\.|\.(?:app|router)\.)(?:get|post|put|delete|patch|use)\s*\(/ },
];

/** Pre-compiled regexes from DANGEROUS_PATH_PATTERNS for fast matching. */
const DANGEROUS_PATH_REGEXES: RegExp[] = DANGEROUS_PATH_PATTERNS.map(globToRegex);

// NOTE: There is also a canonical simpleGlobMatch in src/verification/glob-match.ts
// (full regex-based). This globToRegex is a separate conversion function that returns
// a RegExp rather than performing a match — kept local because the API shape differs.

// ─── Glob matching ─────────────────────────────────────────────────────

/**
 * Simple glob pattern to regex conversion.
 * Supports:
 *   **  — matches everything (including path separators)
 *   *   — matches within a single path segment
 *   ?   — matches a single character
 * All other characters are regex-escaped.
 *
 * Patterns are anchored to match the full file path.
 */
function globToRegex(pattern: string): RegExp {
  let regexStr = "^";
  let i = 0;

  while (i < pattern.length) {
    const ch = pattern[i];

    if (ch === "*" && i + 1 < pattern.length && pattern[i + 1] === "*") {
      // ** — match everything
      if (i + 2 < pattern.length && pattern[i + 2] === "/") {
        // **/ — optional directory prefix
        regexStr += "(?:.+/)?";
        i += 3;
      } else if (i > 0 && i + 2 === pattern.length) {
        // trailing **
        regexStr += ".*";
        i += 2;
      } else {
        regexStr += ".*";
        i += 2;
      }
    } else if (ch === "*") {
      // * — match within a path segment (no /)
      regexStr += "[^/]*";
      i++;
    } else if (ch === "?") {
      regexStr += "[^/]";
      i++;
    } else if (ch === ".") {
      regexStr += "\\.";
      i++;
    } else {
      // Escape regex special characters
      regexStr += ch.replace(/[.+^${}()|[\]\\]/g, "\\$&");
      i++;
    }
  }

  regexStr += "$";
  return new RegExp(regexStr);
}

/**
 * Check if a file path matches any of the dangerous patterns.
 * Normalizes the path using path.resolve() before matching.
 */
export async function matchesDangerousPath(
  filePath: string,
  patterns: readonly string[] = DANGEROUS_PATH_PATTERNS,
  regexes: readonly RegExp[] = DANGEROUS_PATH_REGEXES,
): Promise<string | null> {
  const normalizedPath = resolve(filePath);
  const effectiveRegexes = patterns === DANGEROUS_PATH_PATTERNS ? regexes : patterns.map(globToRegex);
  for (let i = 0; i < effectiveRegexes.length; i++) {
    if (effectiveRegexes[i].test(normalizedPath)) {
      return patterns[i];
    }
  }
  return null;
}

/**
 * Check if a file appears to be auto-generated by scanning its first N lines
 * for known auto-generated markers.
 *
 * @param absolutePath - Absolute path to the file to check
 * @returns true if the file appears auto-generated, false otherwise
 */
interface AutoGenResult {
  isAuto: boolean;
  marker?: string;
  line?: number;
}

async function detectAutoGenerated(absolutePath: string): Promise<AutoGenResult> {
  try {
    await stat(absolutePath);
  } catch {
    return { isAuto: false };
  }

  let fd: Awaited<ReturnType<typeof open>> | null = null;
  try {
    fd = await open(absolutePath, "r");
    const chunk = await fd.read(
      Buffer.alloc(AUTO_GENERATED_CHECK_LINES * 100),
      0,
      AUTO_GENERATED_CHECK_LINES * 100,
      0,
    );
    const text = chunk.buffer.toString("utf8", 0, chunk.bytesRead);
    const lines = text.split("\n").slice(0, AUTO_GENERATED_CHECK_LINES);

    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      for (const marker of AUTO_GENERATED_MARKERS) {
        if (trimmed.toLowerCase().includes(marker.toLowerCase())) {
          return { isAuto: true, marker, line: i + 1 };
        }
      }
    }
    return { isAuto: false };
  } finally {
    if (fd) await fd.close();
  }
}

export async function isAutoGenerated(absolutePath: string): Promise<boolean> {
  return (await detectAutoGenerated(absolutePath)).isAuto;
}

/**
 * Assert that a file is editable, throwing an error if it appears auto-generated.
 *
 * @param absolutePath - Absolute path to the file
 * @param displayPath - Display path for error messages
 * @throws Error if the file appears to be auto-generated
 */
export async function assertEditableFile(
  absolutePath: string,
  displayPath: string,
): Promise<void> {
  if (loadConfig().editAutogen) return;
  const result = await detectAutoGenerated(absolutePath);
  if (!result.isAuto) return;

  throw new Error(
    `Cannot edit "${displayPath}": this file appears to be auto-generated (contains "${result.marker}" at line ${result.line}).\n` +
      `To edit this file anyway, set SMART_EDIT_EDIT_AUTOGEN=true.`,
  );
}

// ─── Content scanning ──────────────────────────────────────────────────

interface SymbolMatch {
  name: string;
  editIndex: number;
}

/**
 * Scan all edits for dangerous symbol patterns.
 * Deduplicates so the same pattern across multiple edits is reported once.
 *
 * Covers every text-bearing edit form:
 *  - oldText / newText (text replacement)
 *  - target.replaceBody / insertBefore / insertAfter (symbolic edits)
 *  - target.pattern / target.replacement (structural ast-grep edits)
 * plus any extra content (e.g. add-file bodies) passed separately.
 */
function scanEditsForDangerousSymbols(
  edits: readonly EditItem[],
  patterns: ReadonlyArray<{ name: string; regex: RegExp }> = DANGEROUS_SYMBOL_PATTERNS,
  extraContent: readonly string[] = [],
): SymbolMatch[] {
  const seen = new Set<string>();
  const results: SymbolMatch[] = [];

  const checkText = (text: string, editIndex: number): void => {
    for (const pattern of patterns) {
      if (seen.has(pattern.name)) continue; // already reported
      if (pattern.regex.test(text)) {
        seen.add(pattern.name);
        results.push({ name: pattern.name, editIndex });
      }
    }
  };

  for (let i = 0; i < edits.length; i++) {
    const edit = edits[i];
    const textsToCheck: string[] = [];

    if (edit.oldText) textsToCheck.push(edit.oldText);
    if (edit.newText) textsToCheck.push(edit.newText);
    const t = edit.target;
    if (t?.replaceBody) textsToCheck.push(t.replaceBody);
    if (t?.insertBefore) textsToCheck.push(t.insertBefore);
    if (t?.insertAfter) textsToCheck.push(t.insertAfter);
    if (t?.pattern) textsToCheck.push(t.pattern);
    if (t?.replacement) textsToCheck.push(t.replacement);

    for (const text of textsToCheck) checkText(text, i);
  }

  for (const text of extraContent) checkText(text, -1);

  return results;
}

// ─── Default config ────────────────────────────────────────────────────

function defaultConfig(): ApprovalConfig {
  return {
    level: readApprovalLevelFromEnv(),
    dangerousPathPatterns: DANGEROUS_PATH_PATTERNS,
    dangerousSymbolPatterns: DANGEROUS_SYMBOL_PATTERNS,
    criticalLineRange: 30,
  };
}

// ─── Main entry point ──────────────────────────────────────────────────

/**
 * Run risk-warning checks for a given file path and edit items.
 *
 * Three levels of checking:
 *   1. File path against dangerous path patterns
 *   2. Edit content against dangerous symbol patterns (all text forms)
 *   3. Edit span within critical first-N lines of entry points (optional)
 *
 * Returns a SafetyCheckResult with warnings (never throws for danger).
 * These are advisory risk warnings only — they never block or prompt.
 *
 * @param extraContent Additional text to scan (e.g. add-file bodies).
 */
export async function checkEditSafety(
  filePath: string,
  edits: readonly EditItem[],
  config?: Partial<ApprovalConfig>,
  extraContent: readonly string[] = [],
): Promise<SafetyCheckResult> {
  const cfg: ApprovalConfig = { ...defaultConfig(), ...config };

  if (cfg.level === "never_prompt") {
    return { safe: true, warnings: [], level: cfg.level };
  }

  const warnings: string[] = [];

  // ── 1. Check file path against dangerous patterns ─────────────
  // Resolve symlinks and normalize path before checking
  let resolvedPath = filePath;
  try {
    resolvedPath = await realpath(filePath);
  } catch {
    // Fall back to resolved path if realpath fails
    resolvedPath = resolve(filePath);
  }
  const matchedPath = await matchesDangerousPath(resolvedPath, cfg.dangerousPathPatterns);
  if (matchedPath) {
    warnings.push(
      `⚠️ Risk warning: editing "${filePath}" matches dangerous path pattern "${matchedPath}". ` +
        `Review this change carefully before proceeding.`,
    );
  }

  // ── 1.5. Check for auto-generated files ───────────────────────────
  const autoGenerated = await isAutoGenerated(resolvedPath);
  if (autoGenerated) {
    warnings.push(
      `⚠️ Risk warning: file appears auto-generated. Editing it may cause build artifacts to diverge.`,
    );
  }

  // ── 2. Check edit content against dangerous symbol patterns ───
  const symbolMatches = scanEditsForDangerousSymbols(edits, cfg.dangerousSymbolPatterns, extraContent);
  if (symbolMatches.length > 0) {
    const patternsList = symbolMatches.map((m) => m.name).join(", ");
    warnings.push(
      `⚠️ Risk warning: edit content matches dangerous patterns: ${patternsList}. ` +
      `Review these changes carefully before proceeding.`,
    );
  }

  // ── 3. For prompt_always, emit a generic note on safe edits ───
  if (cfg.level === "prompt_always" && warnings.length === 0) {
    warnings.push(
      `ℹ️ Risk check: editing "${filePath}" — no dangerous patterns detected. Proceed with standard caution.`,
    );
  }

  return {
    safe: matchedPath === null && symbolMatches.length === 0 && !autoGenerated,
    warnings,
    level: cfg.level,
  };
}